package tbx;

import java.util.ArrayList;
import java.util.List;
import lemon.LexicalEntry;
import lemon.LexicalSense;


/**
 *
 * @author admin
 */
public class TBX {
    static List<LexicalSense> senses = new ArrayList();

    public static void main(String[] args)  {

        LexicalSense ls = new LexicalSense("Work");
        LexicalEntry le1 = new LexicalEntry("Obra", "es");
        LexicalEntry le2 = new LexicalEntry("Work", "en");
        ls.addEntry(le1);
        ls.addEntry(le2);

        senses.add(ls);
        
        String xml = getXML(senses);
        System.out.println(xml);
        
        
    }
    
    public static String getXML(List<LexicalSense> senses)
    {
        String xml="";
        xml+=getXMLHeader();
        
        for(LexicalSense ls : senses)
        {
            xml+=ls.getXML();
        }
        
        xml+=getXMLTail();
        return xml;
    }
    
    public static String getXMLHeader() {
        String header = "<martif type=\"TBX-Default\" xml:lang=\"en\">\n"
                + "  <martifHeader>\n"
                + "    <fileDesc>\n"
                + "      <sourceDesc>\n"
                + "        <p>This file has been generated by the LIDER project team.</p>\n"
                + "      </sourceDesc>\n"
                + "    </fileDesc>\n"
                + "    <encodingDesc>\n"
                + "      <p type=\"XCSURI\">TBXXCS.xcs</p>\n"
                + "    </encodingDesc>\n"
                + "  </martifHeader><text>\n<body>\n";
        return header;
    }

    public static String getXMLTail() {
        String tail = "</body>\n"
                + "</text>\n"
                + "</martif>";
        return tail;
    }

}
